/** Typed sample data matching the API contracts — used by tests and the showcase app. */
import type {
  ArenaSeatMap,
  CinemaSeatMap,
  CinemaSeats,
  EventDetail,
  EventSummary,
  Fan,
  HallSeatMap,
  Hold,
  Order,
  QueueStatus,
  Refund,
  RefundOptions,
  ResaleListing,
  StadiumSeatMap,
  Ticket,
  User,
} from "@repo/contracts";

export const matchSummary: EventSummary = {
  id: "evt_nile_delta",
  slug: "nile-fc-vs-delta-sc",
  kind: "match",
  layout: "stadium",
  category: "Premier League",
  title: "Nile FC vs Delta SC",
  tag: "Premier League · Matchday 12",
  art: "Nile v Delta",
  theme: "pitch",
  startsAt: "2026-10-18T20:00:00+03:00",
  venue: { name: "Capital Stadium", area: "Cairo", city: "cairo" },
  priceFrom: 75,
  status: "queue",
  statusLabel: "Waiting room open",
  requiresFanId: true,
  maxPerOrder: 4,
  serviceFee: 15,
  homeTeam: { name: "Nile FC", short: "NFC" },
  awayTeam: { name: "Delta SC", short: "DSC" },
};

export const concertSummary: EventSummary = {
  id: "evt_layla_nour",
  slug: "layla-nour-live-in-cairo",
  kind: "concert",
  layout: "arena",
  category: "Concerts",
  title: "Layla Nour — Live in Cairo",
  subtitle: "with special guests The Felucca Band",
  tag: "Concert · Pop",
  art: "Layla Nour Live",
  theme: "plum",
  startsAt: "2026-10-30T20:00:00+03:00",
  venue: { name: "Nile Arena", area: "New Cairo", city: "cairo" },
  priceFrom: 450,
  status: "few_left",
  statusLabel: "Few left",
  requiresFanId: false,
  maxPerOrder: 8,
  serviceFee: 25,
};

export const comingSoonSummary: EventSummary = {
  ...matchSummary,
  id: "evt_egypt",
  slug: "egypt-vs-opponent",
  title: "Egypt vs [Opponent]",
  tag: "National team · Qualifier",
  category: "National team",
  startsAt: "2026-11-14T21:00:00+02:00",
  status: "coming_soon",
  statusLabel: "Coming soon",
  priceFrom: 100,
  homeTeam: { name: "Egypt", short: "EGY" },
  awayTeam: { name: "[Opponent]", short: "TBC" },
};

export const matchDetail: EventDetail = {
  ...matchSummary,
  headline: "Saturday 18 October · Kick-off 20:00 · Gates open 18:00 · Capital Stadium, Cairo",
  description: "Derby day.",
  saleOpensAt: "2026-10-04T14:30:00+03:00",
  gatesOpenAt: "18:00",
  badges: ["Fan ID required", "Max 4 tickets per order", "Separate home & away zones"],
  priceTable: [
    { name: "VIP lounge", where: "West upper tier", price: 600, availability: "few_left", availabilityLabel: "Few left" },
    { name: "Category 1", where: "West stand", price: 250, availability: "available", availabilityLabel: "Available" },
    { name: "Away fans", where: "South curve", price: 75, availability: "restricted", availabilityLabel: "Delta SC fans only" },
  ],
  priceNote: "A 15 EGP service fee per ticket is added at checkout.",
  gates: [
    { gates: "Gates 1–4", area: "North curve" },
    { gates: "Gates 5–8", area: "West stand & VIP" },
  ],
  gatesNote: "Parking P2 and P3 open early.",
  rulesTitle: "Before you buy",
  rules: ["Every ticket is tied to an approved Fan ID.", "One ticket per Fan ID."],
  faqs: [
    { question: "How does the waiting room work?", answer: "Everyone inside gets a random place in line." },
    { question: "When do I get the QR code?", answer: "24 hours before kick-off." },
  ],
  queueEnabled: true,
  presaleCodeEnabled: false,
};

export const concertDetail: EventDetail = {
  ...concertSummary,
  headline: "Fri 30 Oct · Doors 19:00 · Nile Arena, New Cairo",
  description: "One night only.",
  doorsAt: "19:00",
  badges: [],
  priceTable: [
    { name: "General admission", where: "Standing, main floor", price: 450, availability: "available", availabilityLabel: "Available" },
    { name: "Golden Circle", where: "Standing, closest to the stage", price: 900, availability: "few_left", availabilityLabel: "Few left" },
  ],
  priceNote: "Max 8 tickets per order · 25 EGP service fee per ticket",
  rulesTitle: "Good to know",
  rules: ["Small bags only."],
  faqs: [{ question: "Do I need a Fan ID for concerts?", answer: "No." }],
  runningOrder: [
    { time: "19:00", label: "Doors open" },
    { time: "21:15", label: "Layla Nour", headline: true },
  ],
  facts: [
    { label: "DATE", value: "Friday 30 October" },
    { label: "VENUE", value: "Nile Arena, New Cairo" },
  ],
  promoter: "Nile Live Productions",
  scarcityNote: "Golden Circle: few left",
  queueEnabled: false,
  presaleCodeEnabled: true,
};

export const fans: Fan[] = [
  { id: "fan_omar", name: "Omar K. (you)", initials: "OK", fanIdMasked: "Fan ID •••• 4821", status: "approved", isSelf: true },
  { id: "fan_youssef", name: "Youssef A.", initials: "YA", fanIdMasked: "Fan ID •••• 1907", status: "approved", isSelf: false },
  {
    id: "fan_hassan",
    name: "Hassan M.",
    initials: "HM",
    fanIdMasked: "Fan ID under review — can’t buy yet",
    status: "under_review",
    isSelf: false,
  },
];

export const user: User = {
  id: "usr_omar",
  fullName: "Omar Khaled",
  initials: "OK",
  phoneMasked: "+20 10•• ••• 482",
  email: "omar.k@mail.com",
  fanId: { status: "approved", number: "2210 4417 4821", validUntil: "Oct 2029", nameEn: "Omar Khaled" },
  linkedFans: fans,
  credit: 0,
};

const row = (label: string, seats: string) => ({ label, seats });

export const stadiumMap: StadiumSeatMap = {
  layout: "stadium",
  zones: [
    {
      id: "vip",
      name: "VIP lounge",
      short: "VIP",
      side: "W",
      where: "West upper tier",
      gates: "5–8",
      note: "Lounge access.",
      price: 600,
      availability: "few_left",
      availabilityLabel: "Few left",
      restricted: false,
    },
    {
      id: "cat1",
      name: "Category 1",
      short: "Category 1",
      side: "W",
      where: "West stand",
      gates: "5–8",
      note: "Covered.",
      price: 250,
      availability: "available",
      availabilityLabel: "Available",
      restricted: false,
    },
    {
      id: "cat2",
      name: "Category 2",
      short: "Category 2",
      side: "E",
      where: "East stand",
      gates: "9–12",
      note: "Open-air.",
      price: 150,
      availability: "available",
      availabilityLabel: "Available",
      restricted: false,
    },
    {
      id: "cat3",
      name: "Category 3",
      short: "Category 3",
      side: "N",
      where: "North curve",
      gates: "1–4",
      note: "Home end.",
      price: 75,
      availability: "high_demand",
      availabilityLabel: "High demand",
      restricted: false,
    },
    {
      id: "away",
      name: "Away fans",
      short: "Away",
      side: "S",
      where: "South curve",
      gates: "13–14",
      note: "Away end.",
      price: 75,
      availability: "restricted",
      availabilityLabel: "Delta SC Fan IDs only",
      restricted: true,
      restrictedLabel: "Delta SC Fan IDs only",
    },
  ],
  blocks: (["N", "W", "E", "S"] as const).flatMap((side) =>
    [1, 2, 3, 4].map((i) => ({
      id: `${side}${i}`,
      side,
      sideName: { N: "North curve", W: "West stand", E: "East stand", S: "South curve" }[side],
      zoneId: { N: "cat3", W: "cat1", E: "cat2", S: "away" }[side],
      category: { N: "Category 3", W: "Category 1", E: "Category 2", S: "Away fans" }[side],
      price: { N: 75, W: 250, E: 150, S: 75 }[side],
      away: side === "S",
      facing: "▶ PITCH IS THIS WAY ▶",
      rows: [row("A", "aaxaw"), row("B", side === "N" && i === 2 ? "xxxxx" : "aaaaa")],
    })),
  ),
};

export const arenaMap: ArenaSeatMap = {
  layout: "arena",
  note: "Accessible platform at Entrance C.",
  ticketTypes: [
    {
      id: "gc",
      name: "Golden Circle",
      description: "Standing, closest to the stage",
      mapLabel: "Golden Circle · standing",
      price: 900,
      swatch: "#3B1F6B",
      remaining: 40,
      tag: "Few left",
    },
    {
      id: "ga",
      name: "General admission",
      description: "Standing, main floor",
      mapLabel: "General admission · standing",
      price: 450,
      swatch: "#6B4FA0",
      remaining: 1200,
    },
    {
      id: "vip",
      name: "VIP package",
      description: "Box seat, lounge",
      mapLabel: "VIP boxes & lounge",
      price: 2500,
      swatch: "#121512",
      remaining: 6,
      tag: "6 left",
    },
  ],
};

export const hallMap: HallSeatMap = {
  layout: "hall",
  tiers: [
    { id: "A", name: "Category A", where: "Stalls rows A–B", price: 600, swatch: "#5A3A8C", edge: "#3B1F6B", onSwatch: "#FFFFFF" },
    { id: "D", name: "Balcony", where: "Row M", price: 150, swatch: "#E4DCF2", edge: "#8A70BD", onSwatch: "#121512" },
  ],
  sections: [
    { id: "stalls", title: "STALLS", rows: [{ label: "A", tierId: "A", seats: "aaxaaa", aisles: [2, 4] }] },
    { id: "balcony", title: "BALCONY", rows: [{ label: "M", tierId: "D", seats: "awaa", aisles: [2] }] },
  ],
};

export const cinemaMap: CinemaSeatMap = {
  layout: "cinema",
  screen: "Screen 4",
  showtimes: [
    {
      id: "st_0_0",
      date: "2026-10-02",
      dayLabel: "Today",
      dayNumber: "2",
      time: "13:30",
      format: "2D",
      availability: "good",
      availabilityLabel: "Good availability",
      prices: { standard: 150, vip: 300 },
    },
    {
      id: "st_0_2",
      date: "2026-10-02",
      dayLabel: "Today",
      dayNumber: "2",
      time: "19:00",
      format: "IMAX",
      availability: "filling",
      availabilityLabel: "Filling up",
      prices: { standard: 220, vip: 380 },
    },
    {
      id: "st_1_0",
      date: "2026-10-03",
      dayLabel: "Sat",
      dayNumber: "3",
      time: "13:30",
      format: "2D",
      availability: "almost_full",
      availabilityLabel: "Almost full",
      prices: { standard: 150, vip: 300 },
    },
  ],
};

export const cinemaSeats: CinemaSeats = {
  showtimeId: "st_0_2",
  rows: [
    { label: "A", vip: false, seats: "waxa", aisles: [2] },
    { label: "J", vip: true, seats: "aaxa", aisles: [2] },
  ],
};

export const hold: Hold = {
  id: "hold_1",
  eventId: matchSummary.id,
  eventSlug: matchSummary.slug,
  eventTitle: matchSummary.title,
  eventTag: "PREMIER LEAGUE · MATCHDAY 12",
  eventMeta: "Sat 18 Oct · 20:00 · Capital Stadium",
  eventKind: "match",
  theme: "pitch",
  expiresAt: "2026-10-01T10:10:00+03:00",
  lines: [
    { label: "Category 1 · West stand × 2", quantity: 2, unitPrice: 250, amount: 500 },
    { label: "Service fee × 2", quantity: 2, unitPrice: 15, amount: 30 },
  ],
  seats: ["W3 · Row F · Seat 7", "W3 · Row F · Seat 8"],
  ticketCount: 2,
  subtotal: 500,
  fees: 30,
  discount: 0,
  total: 530,
  holdersTitle: "Ticket holders",
  holders: [
    { initials: "OK", name: "Omar K.", detail: "Fan ID •••• 4821" },
    { initials: "YA", name: "Youssef A.", detail: "Fan ID •••• 1907" },
  ],
  holdersNote: "Tickets are tied to these Fan IDs.",
  backHref: "/events/nile-fc-vs-delta-sc/tickets",
};

const baseTicket: Ticket = {
  id: "tkt_1",
  code: "MP-58213",
  orderId: "ord_1",
  eventId: matchSummary.id,
  eventSlug: matchSummary.slug,
  eventKind: "match",
  theme: "pitch",
  variant: "ink",
  status: "valid",
  kindLabel: "PREMIER LEAGUE · MATCHDAY 12",
  title: "Nile FC vs Delta SC",
  startsAt: matchSummary.startsAt,
  dateLabel: "18 OCT, 2026",
  whenLabel: "Sat 18 Oct · Kick-off 20:00 · Gates 18:00",
  time: "20:00",
  timeLabel: "Kick-off · gates open 18:00",
  venueName: "Capital Stadium",
  venueArea: "Cairo",
  priceLabel: "[Price · 250 EGP]",
  price: 250,
  fields: [
    { key: "Seat", value: "18" },
    { key: "Block", value: "W3" },
    { key: "Row", value: "L" },
    { key: "Gate", value: "7" },
  ],
  seatLabel: "W3 · Row L · Seat 18",
  holderName: "Omar K.",
  holderInitials: "OK",
  holderDetail: "Fan ID •••• 4821 · bring your ID card",
  holderDate: "18.10.26",
  position: { index: 1, of: 2 },
  progress: 70,
  qrReady: true,
  qrUnlockLabel: "Appears Fri 17 Oct at 20:00, 24 hours before kick-off.",
  entryInfo: "Enter through Gate 7.",
  transferMode: "fan_id",
  transferNote: "Matches: tickets can only go to an approved Fan ID.",
  refundable: false,
  refundNote: "Refund not available — sell on official resale instead",
  resaleAllowed: true,
};

export const matchTicket = baseTicket;
export const matchTicket2: Ticket = {
  ...baseTicket,
  id: "tkt_2",
  code: "MP-58214",
  holderName: "Youssef A.",
  holderInitials: "YA",
  position: { index: 2, of: 2 },
  seatLabel: "W3 · Row L · Seat 19",
};
export const concertTicket: Ticket = {
  ...baseTicket,
  id: "tkt_3",
  code: "MP-60417",
  orderId: "ord_2",
  eventId: concertSummary.id,
  eventSlug: concertSummary.slug,
  eventKind: "concert",
  theme: "plum",
  variant: "lime",
  kindLabel: "CONCERT · POP",
  title: "Layla Nour Live",
  startsAt: concertSummary.startsAt,
  fields: [
    { key: "Area", value: "Golden" },
    { key: "Type", value: "Standing" },
    { key: "Entrance", value: "B" },
    { key: "Ticket", value: "1 / 2" },
  ],
  seatLabel: "Golden · Standing · Entrance B",
  price: 900,
  priceLabel: "[Price · 900 EGP]",
  qrReady: false,
  transferMode: "contact",
  transferNote: "Your friend gets a new QR.",
  refundable: true,
  refundNote: "Refundable until 23 Oct",
};

export const order: Order = {
  id: "ord_1",
  reference: "MP-2410-58213",
  status: "paid",
  eventSlug: matchSummary.slug,
  eventTitle: matchSummary.title,
  eventTag: "PREMIER LEAGUE · MATCHDAY 12",
  eventMeta: "Sat 18 Oct · 20:00 · Capital Stadium",
  eventKind: "match",
  theme: "pitch",
  entryNote: "Gates open 18:00 · Use Gate 7",
  total: 530,
  paymentLabel: "Paid by card •••• 0042",
  createdAt: "2026-10-01T10:05:00+03:00",
  tickets: [matchTicket, matchTicket2],
  nextSteps: [
    { title: "QR appears 24 hours before kick-off", body: "In My tickets." },
    { title: "Bring your ID card", body: "Gate staff check your Fan ID." },
  ],
  parkingOffer: { title: "Add parking for this match", detail: "P2 West · 50 EGP", price: 50 },
};

export const queueWaiting: QueueStatus = {
  id: "q1",
  eventId: matchSummary.id,
  phase: "waiting",
  opensInSeconds: 6,
  ahead: 3412,
  total: 3412,
  etaMinutes: 6,
  progress: 0,
  smsOptIn: false,
  turnWindowMinutes: 10,
};
export const queueInLine: QueueStatus = { ...queueWaiting, phase: "in_line", opensInSeconds: 0, ahead: 1706, etaMinutes: 3, progress: 50 };
export const queueTurn: QueueStatus = { ...queueWaiting, phase: "your_turn", opensInSeconds: 0, ahead: 0, etaMinutes: 0, progress: 100 };

export const refundInReview: Refund = {
  id: "rf_1",
  reference: "RF-2410-0091",
  orderId: "ord_2",
  requestedLabel: "1 OCT",
  eventTitle: "Layla Nour Live",
  detail: "2 × Golden Circle · reason: can’t attend",
  amount: 1800,
  destination: "To card •••• 0042",
  status: "in_review",
  statusLabel: "In review",
  steps: [
    { label: "Requested", when: "1 Oct, 14:02", state: "done" },
    { label: "Reviewing", when: "By 2 Oct", state: "current" },
    { label: "Approved", when: "Tickets cancelled", state: "todo" },
    { label: "Money sent", when: "5–10 working days", state: "todo" },
  ],
  note: "Your tickets stay valid until we approve the refund.",
  noteTone: "neutral",
  canCancel: true,
  secondaryAction: "View order",
};

export const refundDone: Refund = {
  ...refundInReview,
  id: "rf_2",
  reference: "RF-2409-0077",
  eventTitle: "Delta SC vs Red Sea FC",
  status: "refunded",
  statusLabel: "Refunded",
  steps: refundInReview.steps.map((s) => ({ ...s, state: "done" as const })),
  noteTone: "success",
  note: "Refunded in full.",
  canCancel: false,
  secondaryAction: "Download refund receipt",
  refundedTicket: { ...matchTicket, status: "refunded" },
};

export const refundOptions: RefundOptions = {
  orderId: "ord_2",
  reference: "MP-2410-60417",
  eventTitle: "Layla Nour Live",
  eventDateLabel: "30 OCT",
  tickets: [
    { id: "tkt_3", label: "Golden Circle · Ticket 1", meta: "Omar K. · Entrance B · MP-60417", price: 900 },
    { id: "tkt_4", label: "Golden Circle · Ticket 2", meta: "Omar K. · Entrance B · MP-60418", price: 900 },
  ],
  serviceFeePerTicket: 25,
  deadlineNote: "Refundable until Thu 23 Oct",
  methods: [
    {
      id: "card",
      name: "Original card •••• 0042",
      note: "Back to the card you paid with",
      time: "5–10 working days",
      tag: "5–10 days",
      bonusRate: 0,
    },
    {
      id: "credit",
      name: "Matchpass credit",
      note: "Use it on any event",
      time: "Instantly, once approved",
      tag: "+5% bonus",
      bonusRate: 0.05,
    },
  ],
};

export const listings: ResaleListing[] = [
  { id: "lst_1", ticketId: "tkt_x", title: "Cairo Jazz Nights · 2-day", price: 300, payout: 285, status: "listed", detail: "300 EGP" },
  {
    id: "lst_2",
    ticketId: "tkt_y",
    title: "Canal United vs Sinai Stars",
    price: 50,
    payout: 47.5,
    status: "sold",
    detail: "50 EGP · paid out 47.50",
  },
];
